# This is a basic workflow to help you get started with Actions

name: Get RSS To JSON

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 3,15 * * *"
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Python Version
        uses: actions/setup-python@v3
        with:
          python-version: 3.8 # Install the python version needed

      - name: Execute Python script # Run the app.py
        run: python main.py
